// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: example/person3.proto

package person

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/codyaray/proto-go-setter"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (t *Person3) SetId(id int32) {
	t.Id = id
}
