// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: example/person1.proto

package person

import (
	fmt "fmt"

	proto "github.com/gogo/protobuf/proto"

	math "math"

	_ "github.com/confluentinc/proto-go-setter"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (t *Person1) SetName(name string) {
	t.Name = name
}
