// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: example/person5.proto

package person

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/confluentinc/proto-go-setter"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (t *Person5) SetPhoneNumbers(phone_numbers map[string]string) {
	t.PhoneNumbers = phone_numbers
}
